# ruff: noqa: E501
"""النصوص العربية. مختصرة، واثقة، هادئة. فكرة واحدة في كل سطر."""

T: dict[str, str] = {
    # ── عام ───────────────────────────────────────────────────
    "app": "Vigil",
    "tagline": "نظام الحماية",
    "back": "‹ رجوع",
    "refresh": "↻ تحديث",
    "home": "الرئيسية",
    "cancel": "إلغاء",
    "confirm": "تأكيد",
    "yes": "نعم",
    "no": "لا",
    "on": "مفعّل",
    "off": "متوقف",
    "none": "لا شيء",
    "unknown": "غير معروف",
    "page": "{cur} / {total}",
    "next": "التالي ›",
    "prev": "‹ السابق",
    "by": "بواسطة",
    "id": "المعرّف",
    "reason": "السبب",
    "details": "◇ التفاصيل",
    "open_channel": "↗ فتح القناة",
    "working": "◇ جارٍ التنفيذ…",
    "something_wrong": "حدث خطأ.\nتم تسجيل الحدث. حاول مرة أخرى بعد لحظة.",
    "not_permitted": "غير مسموح.",
    "not_active": "هذه القناة غير مفعّلة في Vigil.",
    "toast_saved": "تم الحفظ.",
    "toast_restored": "تمت الاستعادة.",
    "toast_not_permitted": "غير مسموح.",
    "toast_started": "وضع الاحتماء مفعّل.",
    "toast_stopped": "وضع الاحتماء متوقف.",
    "toast_removed": "تمت الإزالة.",
    "toast_added": "تمت الإضافة.",
    "toast_cancelled": "تم الإلغاء.",
    "toast_refreshed": "محدَّث.",
    "toast_nothing": "لا شيء لتنفيذه.",
    "toast_error": "تعذّر إتمام ذلك.",
    "toast_synced": "تمت مزامنة المشرفين.",
    "toast_send_input": "أرسله كرسالة.",
    "input_cancelled": "أُلغي. لم يتغير شيء.",

    # ── البداية / الرئيسية ────────────────────────────────────
    "welcome_title": "✦ Vigil · نظام الحماية",
    "welcome_body": (
        "حماية هادئة ومستمرة لمشرفي القناة.\n\n"
        "<b>كيف يبدأ الأمر</b>\n"
        "1. أضف @{bot} إلى قناتك كمشرف\n"
        "   مع صلاحيتَي <i>إضافة مشرفين</i> و<i>حذف الرسائل</i>.\n"
        "2. فعّل <i>توقيع الرسائل</i> من إعدادات القناة.\n"
        "3. انتظر التفعيل من مالك النظام.\n\n"
        "سيصلك إشعار هنا فور تفعيل القناة."
    ),
    "welcome_no_channels": "لا توجد قنوات مرتبطة بحسابك بعد.",
    "home_title": "✦ Vigil",
    "home_channels": "القنوات",
    "home_channels_line": "{n} تحت الحماية",
    "home_pick": "اختر قناة لفتح لوحة التحكم.",
    "btn_system": "◇ النظام",
    "btn_help": "مساعدة",
    "help_title": "مساعدة",
    "help_body": (
        "<b>ماذا يفعل Vigil</b>\n"
        "كل منشور من مشرف يُفحص على طبقات: الوسائط، الإيموجي المدفوع، إعادة التوجيه، الروابط والمنشن، نوع الكتابة، الطول، ثم فحص الإنجليزية. المخالفة تحذف المنشور وتُنزّل المشرف، مع زر استعادة بضغطة واحدة.\n\n"
        "<b>وضع الاحتماء</b>\n"
        "يُنزّل كل المشرفين المُدارين لفترة أو وفق جدول، ثم يعيد صلاحياتهم بدقة.\n\n"
        "<b>حقيقتان عن Telegram</b>\n"
        "• منشورات القناة لا تحمل اسم الكاتب. يتعرّف Vigil على الكاتب عبر <i>توقيع الرسائل</i>، فأبقِ التوقيعات مفعّلة واجعل ألقاب المشرفين مميزة.\n"
        "• البوت يستطيع تنزيل المشرفين الذين رفعهم هو فقط. أضف المشرفين عبر Vigil ليكونوا تحت الحماية.\n\n"
        "<b>الأوامر</b>\n"
        "/start — الرئيسية\n/id — معرّفك في Telegram\n/cancel — إلغاء الإدخال الحالي"
    ),
    "your_id": "معرّفك · <code>{id}</code>",

    # ── قائمة القنوات ─────────────────────────────────────────
    "chs_title": "القنوات",
    "chs_empty": "لا توجد قنوات بعد.",
    "ch_status_active": "محمية",
    "ch_status_pending": "بانتظار التفعيل",
    "ch_status_suspended": "موقوفة",
    "ch_status_revoked": "ملغاة",
    "ch_status_detached": "أُزيل البوت",

    # ── لوحة القناة ───────────────────────────────────────────
    "sec_channel": "القناة",
    "sec_admins": "المشرفون",
    "sec_shield": "وضع الاحتماء",
    "sec_guard": "حارس المحتوى",
    "admins_summary": "{active} نشط",
    "admins_shielded": "{n} محتمٍ",
    "admins_suspended": "{n} موقوف",
    "admins_attention": "{n} يحتاج انتباهًا",
    "shield_offline": "متوقف",
    "shield_until": "احتماء حتى {until}",
    "shield_manual": "احتماء حتى الإيقاف",
    "shield_next": "التالي · {when}",
    "guard_on": "نشط",
    "guard_off": "معطّل",
    "layer_links": "الروابط",
    "layer_mentions": "المنشن",
    "layer_media": "الوسائط",
    "layer_emoji": "الإيموجي",
    "layer_language": "اللغة",
    "layer_moderation": "الفحص",
    "last_event": "{ago} · {text}",
    "attn_bot_rights": "البوت ينقصه صلاحيات · {rights}",
    "attn_signatures": "يبدو أن التوقيعات متوقفة · لا يمكن نسب المنشورات",
    "attn_unmanaged": "{n} مشرفين رُفعوا خارج Vigil",
    "attn_detached": "أُزيل Vigil من القناة",
    "btn_admins": "المشرفون",
    "btn_shield": "وضع الاحتماء",
    "btn_guard": "حارس المحتوى",
    "btn_emoji": "الإيموجي المدفوع",
    "btn_activity": "السجل",
    "btn_settings": "الإعدادات",
    "btn_channels": "القنوات",
    "btn_bot_rights": "صلاحيات البوت",

    # ── صلاحيات البوت ─────────────────────────────────────────
    "brt_title": "صلاحيات البوت",
    "brt_intro": "ما يملكه Vigil في هذه القناة.",
    "brt_required": "مطلوبة",
    "brt_optional": "اختيارية",
    "brt_missing_hint": "افتح القناة ← المشرفون ← Vigil، وفعّل الصلاحيات الناقصة.",
    "brt_not_admin": "Vigil ليس مشرفًا في هذه القناة.",

    # ── المشرفون ──────────────────────────────────────────────
    "adm_title": "المشرفون",
    "adm_empty": "لا يوجد مشرفون مسجّلون.\nأضف واحدًا، أو زامن القائمة من Telegram.",
    "adm_count": "{n} مسجّل",
    "btn_add_admin": "إضافة مشرف",
    "btn_sync": "↻ مزامنة من Telegram",
    "st_active": "نشط",
    "st_suspended": "موقوف",
    "st_shielded": "محتمٍ",
    "st_unmanaged": "غير مُدار",
    "st_removed": "مُزال",
    "st_owner": "المالك",
    "adm_detail_title": "المشرف",
    "adm_status": "الحالة",
    "adm_rights": "الصلاحيات",
    "adm_no_rights": "لا صلاحيات",
    "adm_title_label": "اللقب",
    "adm_violations": "المخالفات",
    "adm_last_violation": "آخر مخالفة",
    "adm_no_violations": "لا مخالفات",
    "adm_since": "منذ",
    "adm_managed": "تحت الحماية",
    "adm_unmanaged_hint": (
        "رُفع خارج Vigil.\nTelegram لا يسمح للبوت بتنزيل إلا من رفعه بنفسه، لذلك هذا المشرف ليس تحت الحماية.\n\n"
        "<b>لحمايته</b>\nأزل صلاحياته من Telegram، ثم اضغط <i>رفع عبر Vigil</i>."
    ),
    "adm_owner_note": "مالك القناة لا يمكن تنزيله من أحد. مستثنى دائمًا.",
    "adm_exempt": "مستثنى من الاحتماء",
    "btn_suspend": "إيقاف",
    "btn_restore": "↻ استعادة",
    "btn_remove": "إزالة",
    "btn_exempt_on": "استثناء من الاحتماء",
    "btn_exempt_off": "شمول في الاحتماء",
    "btn_reset": "إعادة تعيين الحالة",
    "btn_violations": "المخالفات",
    "btn_adopt": "رفع عبر Vigil",
    "confirm_suspend": "إيقاف <b>{name}</b>؟\nصلاحياته محفوظة ويمكن استعادتها في أي وقت.",
    "confirm_remove": "إزالة <b>{name}</b> من المشرفين؟\nهذا تنزيل كامل. تُحفظ نسخة من الصلاحيات.",
    "suspend_reason_manual": "أوقفه المدير",
    "suspended_ok": "أُوقفت صلاحيات المشرف.",
    "restored_ok": "تمت استعادة المشرف.",
    "restored_dropped": "لم تُستعَد (البوت لا يملكها): {rights}",
    "restored_title_hint": "اللقب «{title}» يجب ضبطه يدويًا — Telegram لا يسمح للبوتات بضبط الألقاب في القنوات.",
    "restore_failed": "تعذّرت الاستعادة.\n{error}",
    "removed_ok": "أُزيل المشرف.",
    "reset_ok": "أُعيد تعيين الحالة.",
    "exempt_on_ok": "مستثنى من وضع الاحتماء.",
    "exempt_off_ok": "مشمول في وضع الاحتماء.",
    "err_not_managed": "رفض Telegram.\nهذا المشرف رُفع خارج Vigil ولا يمكن للبوت تنزيله.",
    "err_bot_rights": "Vigil ينقصه صلاحيات في هذه القناة · {rights}",
    "err_owner": "لا يمكن تغيير مالك القناة.",
    "err_telegram": "خطأ من Telegram.\n{error}",

    # ── إضافة مشرف ────────────────────────────────────────────
    "adda_title": "إضافة مشرف",
    "adda_prompt": (
        "من الذي سيُرفع؟\n\n"
        "• اضغط <b>اختيار مستخدم</b> بالأسفل، أو\n"
        "• وجّه أي رسالة منه، أو\n"
        "• أرسل معرّفه الرقمي."
    ),
    "adda_pick_button": "اختيار مستخدم",
    "adda_invalid": "لا يمكنني استخدام هذا.\nوجّه رسالة منه أو أرسل معرّفًا رقميًا.",
    "adda_is_bot": "البوتات لا يمكن أن تكون مشرفين هنا.",
    "adda_already": "<b>{name}</b> مشرف بالفعل.",
    "adda_preset_title": "صلاحيات {name}",
    "adda_preset_hint": "اختر مجموعة صلاحيات. يمكنك تعديلها لاحقًا من Telegram.",
    "preset_publisher": "ناشر",
    "preset_publisher_desc": "نشر وتعديل وحذف الرسائل",
    "preset_editor": "محرر",
    "preset_editor_desc": "ناشر + القصص والتثبيت",
    "preset_moderator": "مراقب",
    "preset_moderator_desc": "حذف الرسائل، إدارة الرسائل المباشرة، الدعوة",
    "preset_full": "كامل",
    "preset_full_desc": "كل شيء عدا إضافة المشرفين",
    "adda_confirm": "رفع <b>{name}</b> بصفة <b>{preset}</b>؟\n\n{rights}",
    "adda_done": "<b>{name}</b> أصبح مشرفًا تحت الحماية.",
    "adda_dropped": "لم تُمنح (البوت لا يملكها): {rights}",
    "adda_failed": "تعذّر الرفع.\n{error}",
    "adda_hint_join": "إن لم يكن عضوًا بعد، قد يطلب Telegram انضمامه أولًا.",

    # ── حارس المحتوى ──────────────────────────────────────────
    "grd_title": "حارس المحتوى",
    "grd_master": "الحماية",
    "grd_links": "الروابط",
    "grd_mentions": "المنشن",
    "grd_forwards": "إعادة التوجيه",
    "grd_media": "الوسائط",
    "grd_emoji": "الإيموجي المدفوع",
    "grd_language": "اللغات الأجنبية",
    "grd_english_api": "فحص الإنجليزية",
    "grd_foreign_latin": "نص لاتيني غير إنجليزي",
    "grd_char_limit": "حد الأحرف الإنجليزية",
    "grd_length_action": "إجراء تجاوز الحد",
    "grd_violation_action": "إجراء المخالفة",
    "grd_delete_msg": "حذف المنشور المخالف",
    "grd_api_fail": "إذا تعذّر الفحص",
    "grd_notify_system": "إشعار مالك النظام أيضًا",
    "grd_unattributed": "تنبيهات المنشورات غير الموقّعة",
    "act_delete": "حذف المنشور",
    "act_demote": "إيقاف المشرف",
    "act_delete_only": "حذف فقط",
    "act_notify_only": "إشعار فقط",
    "fail_default": "افتراضي النظام",
    "fail_open": "السماح",
    "fail_closed": "اعتباره مخالفة",
    "btn_media_policy": "سياسة الوسائط",
    "btn_categories": "فئات الفحص",
    "btn_set_limit": "ضبط حد الأحرف",
    "limit_prompt": "أرسل الحد الأقصى للأحرف الإنجليزية في المنشور.\nالحالي · {n}. أرسل 0 للتعطيل.",
    "limit_invalid": "أرسل رقمًا صحيحًا بين 0 و4096.",
    "limit_saved": "حد الأحرف أصبح {n}.",
    "grd_footer": "النص العربي لا يغادر الخادم أبدًا. يُفحص النص اللاتيني فقط.",

    # ── سياسة الوسائط ─────────────────────────────────────────
    "med_title": "سياسة الوسائط",
    "med_count": "الصور المسموحة في المنشور",
    "med_hint": "«محدود» يسمح حتى العدد أعلاه في المنشور أو الألبوم.",
    "mt_photo": "صورة",
    "mt_document_image": "صورة كملف",
    "mt_document": "ملف",
    "mt_video": "فيديو",
    "mt_animation": "GIF / متحرك",
    "mt_sticker": "ملصق",
    "mt_video_note": "رسالة فيديو",
    "mt_voice": "رسالة صوتية",
    "mt_audio": "صوت",
    "pol_allow": "سماح",
    "pol_limited": "محدود",
    "pol_block": "منع",

    # ── الفئات ────────────────────────────────────────────────
    "cat_title": "فئات الفحص",
    "cat_hint": "تنطبق على النص الإنجليزي فقط. اضغط للتبديل.",
    "cat_sexual": "محتوى جنسي",
    "cat_minors": "القاصرون",
    "cat_drugs": "المخدرات",
    "cat_violence": "العنف",
    "cat_hate": "الكراهية",
    "cat_harassment": "التحرش",
    "cat_self_harm": "إيذاء النفس",
    "cat_weapons": "الأسلحة",
    "cat_extremism": "التطرف",
    "cat_scam": "الاحتيال والسبام",
    "cat_other": "غير لائق آخر",

    # ── الإيموجي المدفوع ──────────────────────────────────────
    "emo_title": "الإيموجي المدفوع",
    "emo_summary": "{packs} حزمة · {singles} إيموجي مفرد مسموح",
    "emo_empty": "لا شيء مسموح بعد.\nكل إيموجي مخصص في المنشورات سيُعدّ مخالفة حتى تضيف حزمة.",
    "emo_hint": "الإيموجي المخصص خارج هذه القائمة مخالفة.",
    "btn_add_pack": "إضافة حزمة",
    "btn_add_emoji": "إضافة إيموجي",
    "btn_check": "فحص إيموجي",
    "btn_list_ids": "الإيموجي المفرد",
    "btn_sync_pack": "↻ مزامنة",
    "btn_remove_pack": "إزالة",
    "emo_add_pack_prompt": "أرسل رابط الحزمة أو اسمها.\nمثال · <code>https://t.me/addemoji/PackName</code>",
    "emo_add_emoji_prompt": "أرسل الإيموجي المخصص نفسه (واحدًا أو أكثر)، أو معرّفه الرقمي.",
    "emo_check_prompt": "أرسل إيموجي مخصصًا أو معرّفه لمعرفة هل هو مسموح.",
    "emo_pack_added": "أُضيفت الحزمة <b>{title}</b> · {n} إيموجي.",
    "emo_pack_synced": "زُومنت الحزمة <b>{title}</b> · {n} إيموجي.",
    "emo_pack_not_found": "لا توجد حزمة بهذا الاسم.",
    "emo_pack_not_emoji": "هذه حزمة ملصقات، وليست إيموجي مخصصًا.",
    "emo_pack_removed": "أُزيلت الحزمة · {n} إيموجي.",
    "emo_added": "أُضيف {n} إيموجي.",
    "emo_none_found": "لا يوجد إيموجي مخصص في تلك الرسالة.",
    "emo_removed": "أُزيل الإيموجي.",
    "emo_check_allowed": "● مسموح\n{emoji} · <code>{id}</code>\nالحزمة · {set}",
    "emo_check_blocked": "○ غير مسموح\n{emoji} · <code>{id}</code>\nالحزمة · {set}",
    "emo_check_unknown": "Telegram لا يعرف هذا المعرّف.",
    "emo_ids_title": "الإيموجي المفرد",
    "emo_ids_empty": "لم يُضف إيموجي مفرد.",
    "emo_pack_row": "{title} · {n}",

    # ── وضع الاحتماء ──────────────────────────────────────────
    "shd_title": "وضع الاحتماء",
    "shd_intro": "يُنزّل المشرفين المُدارين مؤقتًا ويعيد صلاحياتهم بدقة بعد ذلك.",
    "shd_state": "الحالة",
    "shd_offline": "متوقف",
    "shd_active_until": "احتماء · حتى {until}",
    "shd_active_manual": "احتماء · حتى تُوقفه",
    "shd_ending": "جارٍ استعادة المشرفين…",
    "shd_since": "منذ {since}",
    "shd_members": "{suspended} موقوف · {failed} فشل",
    "shd_exempt": "{n} مستثنى",
    "shd_schedules": "{n} جدول",
    "shd_next": "التالي · {when}",
    "shd_no_next": "لا جدول",
    "btn_start": "تشغيل الآن",
    "btn_stop": "○ إيقاف وضع الاحتماء",
    "btn_schedules": "الجداول",
    "btn_exemptions": "الاستثناءات",
    "btn_history": "السجل",
    "sst_title": "تشغيل وضع الاحتماء",
    "sst_hint": "سيُوقف {n} مشرفين.\n{exempt} مستثنى · {unmanaged} غير مُدار (لن يتأثر).",
    "sst_none": "لا مشرفين مُدارين لإيقافهم.",
    "dur_1h": "ساعة",
    "dur_3h": "3 ساعات",
    "dur_8h": "8 ساعات",
    "dur_manual": "حتى أُوقفه",
    "dur_custom": "مخصص…",
    "sst_custom_prompt": "أرسل المدة.\nأمثلة · <code>90</code> (دقيقة) · <code>2h</code> · <code>1h30m</code>",
    "sst_invalid": "أرسل مدة مثل 45 أو 2h أو 1h30m.",
    "sst_done": "◉ وضع الاحتماء مفعّل.\n{n} مشرفين أُوقفوا · {skipped} تم تخطيهم.",
    "sst_already": "وضع الاحتماء مفعّل بالفعل.",
    "ssp_confirm": "إيقاف وضع الاحتماء واستعادة {n} مشرفين؟",
    "ssp_done": "○ وضع الاحتماء متوقف.\n{restored} استُعيدوا · {failed} فشل.",
    "ssp_failed_hint": "الاستعادات الفاشلة يُعاد محاولتها تلقائيًا كل دقيقة.",
    "sch_title": "الجداول",
    "sch_empty": "لا جداول.\nيمكن تشغيل وضع الاحتماء يوميًا أو في أيام محددة.",
    "sch_row": "{glyph} {days} · {start} → {end}",
    "sch_daily": "كل يوم",
    "sch_weekly": "أسبوعي",
    "btn_add_daily": "إضافة يومي",
    "btn_add_weekly": "إضافة أسبوعي",
    "sch_start_prompt": "أرسل وقت البداية (24 ساعة).\nمثال · <code>22:00</code>",
    "sch_end_prompt": "أرسل وقت النهاية (24 ساعة). يمكن أن يكون بعد منتصف الليل.\nمثال · <code>06:00</code>",
    "sch_invalid_time": "أرسل وقتًا مثل 22:00.",
    "sch_saved": "حُفظ الجدول.",
    "sch_deleted": "حُذف الجدول.",
    "sch_detail_title": "الجدول",
    "sch_days_hint": "اضغط على الأيام للتبديل.",
    "sch_enabled": "مفعّل",
    "sch_disabled": "معطّل",
    "btn_delete_schedule": "حذف",
    "btn_enable": "تفعيل",
    "btn_disable": "تعطيل",
    "day_0": "الاثنين",
    "day_1": "الثلاثاء",
    "day_2": "الأربعاء",
    "day_3": "الخميس",
    "day_4": "الجمعة",
    "day_5": "السبت",
    "day_6": "الأحد",
    "tz_line": "المنطقة الزمنية · {tz}",
    "exm_title": "الاستثناءات",
    "exm_hint": "المشرفون المستثنون يحتفظون بصلاحياتهم أثناء الاحتماء. المالك مستثنى دائمًا.",
    "exm_empty": "لا مشرفين مُدارين.",
    "hist_title": "سجل الاحتماء",
    "hist_empty": "لا جلسات بعد.",
    "hist_row": "{glyph} {start} → {end} · {trigger}",
    "trig_manual": "يدوي",
    "trig_schedule": "جدول",

    # ── السجل ─────────────────────────────────────────────────
    "act_title": "السجل",
    "act_empty": "لم يُسجَّل شيء بعد.",
    "flt_all": "الكل",
    "flt_violations": "المخالفات",
    "flt_admins": "المشرفون",
    "flt_shield": "الاحتماء",
    "flt_channel": "القناة",
    "vio_title": "المخالفات",
    "vio_empty": "لا مخالفات. الأمور هادئة.",
    "vio_row": "{time} · {name} · {kind}",
    "vio_detail_title": "المخالفة",
    "vio_admin": "المشرف",
    "vio_kind": "النوع",
    "vio_rule": "القاعدة",
    "vio_action": "الإجراء",
    "vio_post": "المنشور",
    "vio_excerpt": "مقتطف",
    "vio_api": "الفحص",
    "vio_api_line": "{model} · {category} · {severity}",
    "vio_restored": "استُعيد {when}",

    # ── الإعدادات ─────────────────────────────────────────────
    "set_title": "الإعدادات",
    "set_language": "اللغة",
    "set_timezone": "المنطقة الزمنية",
    "set_managers": "المدراء",
    "set_owner": "المالك",
    "btn_language": "اللغة",
    "btn_timezone": "المنطقة الزمنية",
    "btn_managers": "المدراء",
    "tz_prompt": "أرسل منطقة زمنية بصيغة IANA.\nأمثلة · <code>Asia/Baghdad</code> · <code>Europe/Berlin</code>",
    "tz_invalid": "منطقة زمنية غير معروفة. استخدم اسمًا مثل Asia/Baghdad.",
    "tz_saved": "المنطقة الزمنية أصبحت {tz}.",
    "lang_title": "اللغة",
    "lang_en": "English",
    "lang_ar": "العربية",
    "lang_saved": "تم تحديث اللغة.",
    "mgr_title": "المدراء",
    "mgr_hint": "المدراء يستطيعون استخدام كل أدوات التحكم لهذه القناة.",
    "mgr_row": "{name} · {role}",
    "role_owner": "مالك",
    "role_manager": "مدير",
    "btn_add_manager": "إضافة مدير",
    "mgr_add_prompt": "وجّه رسالة من المدير الجديد أو أرسل معرّفه الرقمي.",
    "mgr_added": "أُضيف المدير.",
    "mgr_removed": "أُزيل المدير.",
    "mgr_cannot_remove_owner": "لا يمكن إزالة المالك.",

    # ── النظام ────────────────────────────────────────────────
    "sys_title": "النظام",
    "sys_channels": "القنوات",
    "sys_channels_line": "{active} نشطة · {pending} معلّقة · {other} أخرى",
    "sys_moderation": "الفحص",
    "sys_moderation_line": "{used} / {budget} اليوم · {model}",
    "sys_moderation_off": "معطّل — لا مفتاح API",
    "sys_shield": "جلسات الاحتماء",
    "sys_uptime": "مدة التشغيل",
    "btn_pending": "معلّقة · {n}",
    "btn_all_channels": "كل القنوات",
    "btn_sys_admins": "مدراء النظام",
    "btn_health": "الصحة",
    "pend_title": "بانتظار التفعيل",
    "pend_empty": "لا قنوات بالانتظار.",
    "pend_card": "<b>{title}</b>\n<code>{id}</code>\nأضافها · {added_by}\nالمالك · {owner}",
    "btn_activate": "● تفعيل",
    "btn_decline": "رفض",
    "activated_ok": "فُعّلت القناة.",
    "declined_ok": "رُفضت القناة.",
    "sysc_title": "كل القنوات",
    "sysc_row": "{glyph} {title}",
    "ch_manage_title": "القناة",
    "btn_ch_suspend": "إيقاف القناة",
    "btn_ch_resume": "استئناف القناة",
    "btn_ch_revoke": "إلغاء",
    "confirm_revoke": "إلغاء <b>{title}</b>؟\nتتوقف الحماية. يحتفظ المشرفون بصلاحياتهم الحالية.",
    "ch_suspended_ok": "أُوقفت القناة.",
    "ch_resumed_ok": "استُؤنفت القناة.",
    "ch_revoked_ok": "أُلغيت القناة.",
    "sysa_title": "مدراء النظام",
    "sysa_hint": "مدراء النظام يستطيعون تفعيل القنوات ورؤية كل القنوات.",
    "sysa_owner": "مالك",
    "sysa_admin": "مدير",
    "btn_add_sysadmin": "إضافة مدير نظام",
    "sysa_add_prompt": "وجّه رسالة من المستخدم أو أرسل معرّفه الرقمي.",
    "sysa_added": "أُضيف مدير النظام.",
    "sysa_removed": "أُزيل مدير النظام.",
    "hlth_title": "الصحة",
    "hlth_db": "قاعدة البيانات",
    "hlth_ok": "سليم",
    "hlth_fail": "غير متاح",
    "hlth_uptime": "مدة التشغيل",
    "hlth_moderation": "واجهة الفحص",
    "hlth_chain": "السلسلة",
    "hlth_requests": "طلبات اليوم",
    "hlth_last_model": "آخر نموذج",
    "hlth_last_error": "آخر خطأ",
    "hlth_cooling": "في فترة تهدئة",
    "hlth_budget_exhausted": "نفدت الميزانية اليومية",
    "hlth_key": "مفتاح OpenRouter",
    "hlth_key_line": "الاستخدام {usage} · الحد {limit} · المجاني اليوم {free_today}",
    "hlth_media_groups": "مخازن الألبومات",
    "hlth_sessions": "جلسات احتماء نشطة",

    # ── البطاقات ──────────────────────────────────────────────
    "card_suspended": "! أُوقفت صلاحيات المشرف",
    "card_deleted": "○ أُزيل المنشور",
    "card_noticed": "! مخالفة للسياسة",
    "card_could_not": "! تعذّر الإيقاف · {why}",
    "why_unattributed": "المنشور غير موقّع",
    "why_unmanaged": "رُفع خارج Vigil",
    "why_owner": "مالك القناة",
    "why_bot_rights": "البوت ينقصه صلاحيات",
    "why_telegram": "خطأ من Telegram",
    "why_already": "موقوف بالفعل",
    "kind_link": "رابط",
    "kind_mention": "منشن",
    "kind_forward": "إعادة توجيه",
    "kind_media": "وسائط",
    "kind_emoji": "إيموجي مدفوع",
    "kind_language": "لغة",
    "kind_length": "طول الإنجليزية",
    "kind_content": "محتوى",
    "reason_link": "رابط في المنشور",
    "reason_mention": "منشن في المنشور",
    "reason_forward": "محتوى مُعاد توجيهه",
    "reason_media": "وسائط خارج السياسة",
    "reason_emoji": "إيموجي مخصص خارج الحزمة المسموحة",
    "reason_language": "نص بلغة خارج السياسة",
    "reason_length": "نص إنجليزي يتجاوز الحد",
    "reason_content": "رصده الفحص",
    "card_rule": "القاعدة",
    "card_post": "المنشور",
    "card_deleted_flag": "حُذف",
    "card_kept_flag": "بقي",
    "card_time": "الوقت",
    "card_channel": "القناة",
    "btn_restore_admin": "↻ إعادته مشرفًا",
    "btn_view_admin": "◇ المشرف",
    "btn_view_violation": "◇ التفاصيل",
    "card_restored_line": "● استُعيد · {by} · {when}",
    "card_unsigned_name": "منشور غير موقّع",
    "card_unknown_name": "توقيع غير معروف «{sig}»",
    "card_ambiguous_name": "توقيع ملتبس «{sig}»",
    "card_shield_on": "◉ وضع الاحتماء مفعّل",
    "card_shield_on_body": "{n} مشرفين أُوقفوا · {skipped} تم تخطيهم\nينتهي · {ends}",
    "ends_manual": "عندما تُوقفه",
    "card_shield_off": "○ وضع الاحتماء متوقف",
    "card_shield_off_body": "{restored} استُعيدوا · {failed} فشل",
    "card_shield_failed_row": "! {name} · {error}",
    "btn_retry_restore": "↻ إعادة محاولة الفاشل",
    "card_api_failure": "! الفحص غير متاح",
    "card_api_failure_body": "المنشورات الإنجليزية {mode} حتى تعود الواجهة.\n{error}",
    "mode_allowed": "يُسمح بها",
    "mode_blocked": "تُعامل كمخالفات",
    "card_unattributed": "! لا يمكن نسب المنشورات",
    "card_unattributed_body": (
        "وصل منشور بلا توقيع، فلا يستطيع Vigil معرفة أي مشرف كتبه.\n\n"
        "فعّل <b>توقيع الرسائل</b> من إعدادات القناة وامنح المشرفين ألقابًا مميزة."
    ),
    "card_ambiguous": "! مشرفان يتشاركان التوقيع نفسه",
    "card_ambiguous_body": "«{sig}» يعود إلى {names}.\nامنحهم ألقابًا مميزة ليمكن نسب المنشورات.",
    "card_bot_rights": "! فقد Vigil صلاحيات",
    "card_bot_rights_body": "الناقص · {rights}\nالحماية والاستعادات متوقفة حتى تُعاد.",
    "card_bot_removed": "! أُزيل Vigil من {title}",
    "card_bot_removed_shield": "كان وضع الاحتماء مفعّلًا. {n} مشرفين لا يمكن استعادتهم حتى يُعاد Vigil.",
    "card_pending": "◇ قناة جديدة بانتظار التفعيل",
    "card_activated": "● {title} أصبحت محمية",
    "card_activated_body": (
        "الحماية نشطة. كل نشاط المشرفين مراقَب الآن.\n\n"
        "<b>قائمة التحقق</b>\n"
        "{rights_line}\n"
        "{signatures_line}\n"
        "{admins_line}"
    ),
    "chk_rights_ok": "● صلاحيات البوت مكتملة",
    "chk_rights_missing": "! ينقص البوت · {rights}",
    "chk_signatures": "◇ فعّل <i>توقيع الرسائل</i> من إعدادات القناة",
    "chk_admins_ok": "● {n} مشرفين تحت الحماية",
    "chk_admins_unmanaged": "! {n} مشرفين رُفعوا خارج Vigil · افتح المشرفين لتبنّيهم",
    "card_unauthorized": "هذه القناة غير مفعّلة في Vigil بعد.\n<b>{title}</b> · <code>{id}</code>\nتم إشعار مالك النظام.",
    "channel_notice_unauthorized": "Vigil · هذه القناة غير مفعّلة في نظام الحماية.",
    "card_reattached": "● عاد Vigil إلى {title}",
    "card_declined": "رُفض تفعيل {title}.",
    "card_external_repromote": "◇ {name} رُفع مجددًا خارج Vigil أثناء إيقافه.",

    # ── تسميات السجل ──────────────────────────────────────────
    "au_channel.unauthorized_attempt": "محاولة قناة غير مصرّحة",
    "au_channel.activated": "تفعيل قناة",
    "au_channel.declined": "رفض قناة",
    "au_channel.suspended": "إيقاف قناة",
    "au_channel.resumed": "استئناف قناة",
    "au_channel.revoked": "إلغاء قناة",
    "au_channel.bot_removed": "إزالة البوت",
    "au_channel.reattached": "إعادة إضافة البوت",
    "au_channel.bot_rights_changed": "تغيّر صلاحيات البوت",
    "au_admin.promoted": "رفع مشرف",
    "au_admin.demoted": "تنزيل مشرف",
    "au_admin.restored": "استعادة مشرف",
    "au_admin.restore_failed": "فشل الاستعادة",
    "au_admin.removed": "إزالة مشرف",
    "au_admin.removed_externally": "إزالة مشرف من Telegram",
    "au_admin.repromoted_externally": "إعادة رفع مشرف من Telegram",
    "au_admin.shield_exempt": "تغيير استثناء الاحتماء",
    "au_admin.reset": "إعادة تعيين حالة مشرف",
    "au_violation": "مخالفة",
    "au_shield.on": "تشغيل الاحتماء",
    "au_shield.off": "إيقاف الاحتماء",
    "au_shield.member_failed": "فشل استعادة في الاحتماء",
    "au_shield.schedule_added": "إضافة جدول",
    "au_shield.schedule_deleted": "حذف جدول",
    "au_shield.schedule_toggled": "تبديل جدول",
    "au_api.failure": "فشل واجهة الفحص",
    "au_telegram.failure": "فشل واجهة Telegram",
    "au_setting.changed": "تغيير إعداد",
    "au_emoji.added": "السماح بإيموجي",
    "au_emoji.removed": "إزالة إيموجي",
    "au_emoji.pack_added": "السماح بحزمة إيموجي",
    "au_emoji.pack_removed": "إزالة حزمة إيموجي",
    "au_system.started": "بدء النظام",
    "au_system.admin_added": "إضافة مدير نظام",
    "au_system.admin_removed": "إزالة مدير نظام",
    "au_manager.added": "إضافة مدير",
    "au_manager.removed": "إزالة مدير",
    "au_post.unattributed": "منشور غير موقّع",
    "au_post.ambiguous": "توقيع ملتبس",
    "au_access.denied": "رفض وصول",
}
