# ruff: noqa: E501
"""English microcopy. Short, confident, calm. One idea per line."""

T: dict[str, str] = {
    # ── common ────────────────────────────────────────────────
    "app": "Vigil",
    "tagline": "Protection System",
    "back": "‹ Back",
    "refresh": "↻ Refresh",
    "home": "Home",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "yes": "Yes",
    "no": "No",
    "on": "On",
    "off": "Off",
    "none": "None",
    "unknown": "Unknown",
    "page": "{cur} / {total}",
    "next": "Next ›",
    "prev": "‹ Prev",
    "by": "by",
    "id": "ID",
    "reason": "Reason",
    "details": "◇ Details",
    "open_channel": "↗ Open channel",
    "working": "◇ Working…",
    "something_wrong": "Something went wrong.\nThe event was recorded. Try again in a moment.",
    "not_permitted": "Not permitted.",
    "not_active": "This channel is not active in Vigil.",
    "toast_saved": "Saved.",
    "toast_restored": "Restored.",
    "toast_not_permitted": "Not permitted.",
    "toast_started": "Shield Mode is on.",
    "toast_stopped": "Shield Mode is off.",
    "toast_removed": "Removed.",
    "toast_added": "Added.",
    "toast_cancelled": "Cancelled.",
    "toast_refreshed": "Up to date.",
    "toast_nothing": "Nothing to do.",
    "toast_error": "Could not complete that.",
    "toast_synced": "Administrators synced.",
    "toast_send_input": "Send it as a message.",
    "input_cancelled": "Cancelled. Nothing changed.",

    # ── start / home ──────────────────────────────────────────
    "welcome_title": "✦ Vigil · Protection System",
    "welcome_body": (
        "Calm, continuous protection for channel administrators.\n\n"
        "<b>How it starts</b>\n"
        "1. Add @{bot} to your channel as an administrator\n"
        "   with <i>Add new admins</i> and <i>Delete messages</i>.\n"
        "2. Turn on <i>Sign messages</i> in the channel settings.\n"
        "3. Wait for activation by the system owner.\n\n"
        "You will be notified here the moment the channel is active."
    ),
    "welcome_no_channels": "No channels are linked to your account yet.",
    "home_title": "✦ Vigil",
    "home_channels": "Channels",
    "home_channels_line": "{n} under protection",
    "home_pick": "Choose a channel to open its control panel.",
    "btn_system": "◇ System",
    "btn_help": "Help",
    "help_title": "Help",
    "help_body": (
        "<b>What Vigil does</b>\n"
        "Every post by an administrator is checked in layers: media, premium emoji, forwards, links and mentions, script, length, then English moderation. A violation removes the post and suspends the administrator, with a one-tap restore.\n\n"
        "<b>Shield Mode</b>\n"
        "Suspends all managed administrators for a period or on a schedule, and restores their exact rights afterwards.\n\n"
        "<b>Two facts about Telegram</b>\n"
        "• Channel posts carry no author. Vigil identifies the author through <i>Sign messages</i>, so keep signatures on and administrator titles unique.\n"
        "• A bot can only demote administrators it promoted itself. Add administrators through Vigil so they are under protection.\n\n"
        "<b>Commands</b>\n"
        "/start — home\n/id — your Telegram ID\n/cancel — abort the current input"
    ),
    "your_id": "Your ID · <code>{id}</code>",

    # ── channels list ─────────────────────────────────────────
    "chs_title": "Channels",
    "chs_empty": "No channels yet.",
    "ch_status_active": "Protected",
    "ch_status_pending": "Pending activation",
    "ch_status_suspended": "Suspended",
    "ch_status_revoked": "Revoked",
    "ch_status_detached": "Bot removed",

    # ── dashboard ─────────────────────────────────────────────
    "sec_channel": "Channel",
    "sec_admins": "Administrators",
    "sec_shield": "Shield Mode",
    "sec_guard": "Content Guard",
    "admins_summary": "{active} active",
    "admins_shielded": "{n} shielded",
    "admins_suspended": "{n} suspended",
    "admins_attention": "{n} attention",
    "shield_offline": "Offline",
    "shield_until": "Shielded until {until}",
    "shield_manual": "Shielded until stopped",
    "shield_next": "Next · {when}",
    "guard_on": "Active",
    "guard_off": "Disabled",
    "layer_links": "Links",
    "layer_mentions": "Mentions",
    "layer_media": "Media",
    "layer_emoji": "Emoji",
    "layer_language": "Language",
    "layer_moderation": "Moderation",
    "last_event": "{ago} · {text}",
    "attn_bot_rights": "Bot is missing rights · {rights}",
    "attn_signatures": "Signatures appear to be off · posts cannot be attributed",
    "attn_unmanaged": "{n} administrators promoted outside Vigil",
    "attn_detached": "Vigil was removed from the channel",
    "btn_admins": "Administrators",
    "btn_shield": "Shield Mode",
    "btn_guard": "Content Guard",
    "btn_emoji": "Premium Emoji",
    "btn_activity": "Activity",
    "btn_settings": "Settings",
    "btn_channels": "Channels",
    "btn_bot_rights": "Bot rights",

    # ── bot rights ────────────────────────────────────────────
    "brt_title": "Bot rights",
    "brt_intro": "What Vigil holds in this channel.",
    "brt_required": "Required",
    "brt_optional": "Optional",
    "brt_missing_hint": "Open the channel → Administrators → Vigil, and enable the missing rights.",
    "brt_not_admin": "Vigil is not an administrator of this channel.",

    # ── administrators ────────────────────────────────────────
    "adm_title": "Administrators",
    "adm_empty": "No administrators registered.\nAdd one, or sync the list from Telegram.",
    "adm_count": "{n} registered",
    "btn_add_admin": "Add administrator",
    "btn_sync": "↻ Sync from Telegram",
    "st_active": "Active",
    "st_suspended": "Suspended",
    "st_shielded": "Shielded",
    "st_unmanaged": "Unmanaged",
    "st_removed": "Removed",
    "st_owner": "Owner",
    "adm_detail_title": "Administrator",
    "adm_status": "Status",
    "adm_rights": "Rights",
    "adm_no_rights": "No rights",
    "adm_title_label": "Title",
    "adm_violations": "Violations",
    "adm_last_violation": "Last violation",
    "adm_no_violations": "No violations",
    "adm_since": "Since",
    "adm_managed": "Under protection",
    "adm_unmanaged_hint": (
        "Promoted outside Vigil.\nTelegram only lets a bot demote administrators it promoted itself, so this administrator is not under protection.\n\n"
        "<b>To protect them</b>\nRemove their admin rights in Telegram, then tap <i>Promote via Vigil</i>."
    ),
    "adm_owner_note": "The channel owner cannot be demoted by anyone. Always exempt.",
    "adm_exempt": "Exempt from Shield Mode",
    "btn_suspend": "Suspend",
    "btn_restore": "↻ Restore",
    "btn_remove": "Remove",
    "btn_exempt_on": "Exempt from Shield",
    "btn_exempt_off": "Include in Shield",
    "btn_reset": "Reset status",
    "btn_violations": "Violations",
    "btn_adopt": "Promote via Vigil",
    "confirm_suspend": "Suspend <b>{name}</b>?\nTheir rights are saved and can be restored at any time.",
    "confirm_remove": "Remove <b>{name}</b> from administrators?\nThis is a full demotion. A snapshot is kept.",
    "suspend_reason_manual": "Suspended by manager",
    "suspended_ok": "Administrator access suspended.",
    "restored_ok": "Administrator restored.",
    "restored_dropped": "Not restored (bot lacks them): {rights}",
    "restored_title_hint": "Custom title “{title}” must be set again manually — Telegram does not let bots set titles in channels.",
    "restore_failed": "Could not restore.\n{error}",
    "removed_ok": "Administrator removed.",
    "reset_ok": "Status reset.",
    "exempt_on_ok": "Exempt from Shield Mode.",
    "exempt_off_ok": "Included in Shield Mode.",
    "err_not_managed": "Telegram refused.\nThis administrator was promoted outside Vigil and cannot be demoted by the bot.",
    "err_bot_rights": "Vigil is missing rights in this channel · {rights}",
    "err_owner": "The channel owner cannot be changed.",
    "err_telegram": "Telegram error.\n{error}",

    # ── add administrator ─────────────────────────────────────
    "adda_title": "Add administrator",
    "adda_prompt": (
        "Who should be promoted?\n\n"
        "• Tap <b>Select user</b> below, or\n"
        "• forward any message from them, or\n"
        "• send their numeric ID."
    ),
    "adda_pick_button": "Select user",
    "adda_invalid": "That is not a user I can use.\nForward a message from them or send a numeric ID.",
    "adda_is_bot": "Bots cannot be administrators here.",
    "adda_already": "<b>{name}</b> is already an administrator.",
    "adda_preset_title": "Rights for {name}",
    "adda_preset_hint": "Choose a set of rights. You can refine later in Telegram.",
    "preset_publisher": "Publisher",
    "preset_publisher_desc": "Post, edit and delete messages",
    "preset_editor": "Editor",
    "preset_editor_desc": "Publisher + stories and pinning",
    "preset_moderator": "Moderator",
    "preset_moderator_desc": "Delete messages, manage direct messages, invite",
    "preset_full": "Full",
    "preset_full_desc": "Everything except adding admins",
    "adda_confirm": "Promote <b>{name}</b> as <b>{preset}</b>?\n\n{rights}",
    "adda_done": "<b>{name}</b> is now an administrator under protection.",
    "adda_dropped": "Not granted (bot lacks them): {rights}",
    "adda_failed": "Could not promote.\n{error}",
    "adda_hint_join": "If they are not a member yet, Telegram may require them to join first.",

    # ── content guard ─────────────────────────────────────────
    "grd_title": "Content Guard",
    "grd_master": "Protection",
    "grd_links": "Links",
    "grd_mentions": "Mentions",
    "grd_forwards": "Forwards",
    "grd_media": "Media",
    "grd_emoji": "Premium emoji",
    "grd_language": "Foreign scripts",
    "grd_english_api": "English moderation",
    "grd_foreign_latin": "Non-English Latin text",
    "grd_char_limit": "English letter limit",
    "grd_length_action": "Over-limit action",
    "grd_violation_action": "Violation action",
    "grd_delete_msg": "Delete offending post",
    "grd_api_fail": "If moderation is unavailable",
    "grd_notify_system": "Also notify system owner",
    "grd_unattributed": "Unsigned-post alerts",
    "act_delete": "Delete post",
    "act_demote": "Suspend admin",
    "act_delete_only": "Delete only",
    "act_notify_only": "Notify only",
    "fail_default": "System default",
    "fail_open": "Allow",
    "fail_closed": "Treat as violation",
    "btn_media_policy": "Media policy",
    "btn_categories": "Moderation categories",
    "btn_set_limit": "Set letter limit",
    "limit_prompt": "Send the maximum number of English letters allowed in a post.\nCurrent · {n}. Send 0 to disable.",
    "limit_invalid": "Send a whole number between 0 and 4096.",
    "limit_saved": "Letter limit set to {n}.",
    "grd_footer": "Arabic text never leaves the server. Only Latin-script text is moderated.",

    # ── media policy ──────────────────────────────────────────
    "med_title": "Media policy",
    "med_count": "Allowed images per post",
    "med_hint": "“Limited” allows up to the count above per post or album.",
    "mt_photo": "Photo",
    "mt_document_image": "Image as file",
    "mt_document": "Document",
    "mt_video": "Video",
    "mt_animation": "GIF / animation",
    "mt_sticker": "Sticker",
    "mt_video_note": "Video message",
    "mt_voice": "Voice message",
    "mt_audio": "Audio",
    "pol_allow": "Allow",
    "pol_limited": "Limited",
    "pol_block": "Block",

    # ── categories ────────────────────────────────────────────
    "cat_title": "Moderation categories",
    "cat_hint": "Applies to English text only. Tap to toggle.",
    "cat_sexual": "Sexual content",
    "cat_minors": "Minors",
    "cat_drugs": "Drugs",
    "cat_violence": "Violence",
    "cat_hate": "Hate",
    "cat_harassment": "Harassment",
    "cat_self_harm": "Self-harm",
    "cat_weapons": "Weapons",
    "cat_extremism": "Extremism",
    "cat_scam": "Scams & spam",
    "cat_other": "Other inappropriate",

    # ── premium emoji ─────────────────────────────────────────
    "emo_title": "Premium Emoji",
    "emo_summary": "{packs} packs · {singles} single emoji allowed",
    "emo_empty": "Nothing allowed yet.\nEvery custom emoji in a post will count as a violation until you add a pack.",
    "emo_hint": "Custom emoji outside this list are violations.",
    "btn_add_pack": "Add pack",
    "btn_add_emoji": "Add emoji",
    "btn_check": "Check emoji",
    "btn_list_ids": "Single emoji",
    "btn_sync_pack": "↻ Sync",
    "btn_remove_pack": "Remove",
    "emo_add_pack_prompt": "Send the pack link or name.\nExample · <code>https://t.me/addemoji/PackName</code>",
    "emo_add_emoji_prompt": "Send the custom emoji itself (one or more), or its numeric ID.",
    "emo_check_prompt": "Send a custom emoji or its ID to check whether it is allowed.",
    "emo_pack_added": "Pack <b>{title}</b> added · {n} emoji.",
    "emo_pack_synced": "Pack <b>{title}</b> synced · {n} emoji.",
    "emo_pack_not_found": "No pack with that name.",
    "emo_pack_not_emoji": "That set is a sticker pack, not custom emoji.",
    "emo_pack_removed": "Pack removed · {n} emoji.",
    "emo_added": "{n} emoji added.",
    "emo_none_found": "No custom emoji in that message.",
    "emo_removed": "Emoji removed.",
    "emo_check_allowed": "● Allowed\n{emoji} · <code>{id}</code>\nPack · {set}",
    "emo_check_blocked": "○ Not allowed\n{emoji} · <code>{id}</code>\nPack · {set}",
    "emo_check_unknown": "Telegram does not know that emoji ID.",
    "emo_ids_title": "Single emoji",
    "emo_ids_empty": "No single emoji added.",
    "emo_pack_row": "{title} · {n}",

    # ── shield mode ───────────────────────────────────────────
    "shd_title": "Shield Mode",
    "shd_intro": "Temporarily suspends managed administrators and restores their exact rights afterwards.",
    "shd_state": "State",
    "shd_offline": "Offline",
    "shd_active_until": "Shielded · until {until}",
    "shd_active_manual": "Shielded · until you stop it",
    "shd_ending": "Restoring administrators…",
    "shd_since": "Since {since}",
    "shd_members": "{suspended} suspended · {failed} failed",
    "shd_exempt": "{n} exempt",
    "shd_schedules": "{n} schedules",
    "shd_next": "Next · {when}",
    "shd_no_next": "No schedule",
    "btn_start": "Start now",
    "btn_stop": "○ Stop Shield Mode",
    "btn_schedules": "Schedules",
    "btn_exemptions": "Exemptions",
    "btn_history": "History",
    "sst_title": "Start Shield Mode",
    "sst_hint": "{n} administrators will be suspended.\n{exempt} exempt · {unmanaged} unmanaged (not affected).",
    "sst_none": "No managed administrators to suspend.",
    "dur_1h": "1 hour",
    "dur_3h": "3 hours",
    "dur_8h": "8 hours",
    "dur_manual": "Until I stop it",
    "dur_custom": "Custom…",
    "sst_custom_prompt": "Send a duration.\nExamples · <code>90</code> (minutes) · <code>2h</code> · <code>1h30m</code>",
    "sst_invalid": "Send a duration like 45, 2h or 1h30m.",
    "sst_done": "◉ Shield Mode is on.\n{n} administrators suspended · {skipped} skipped.",
    "sst_already": "Shield Mode is already on.",
    "ssp_confirm": "Stop Shield Mode and restore {n} administrators?",
    "ssp_done": "○ Shield Mode is off.\n{restored} restored · {failed} failed.",
    "ssp_failed_hint": "Failed restores are retried automatically every minute.",
    "sch_title": "Schedules",
    "sch_empty": "No schedules.\nShield Mode can run every day or on chosen weekdays.",
    "sch_row": "{glyph} {days} · {start} → {end}",
    "sch_daily": "Every day",
    "sch_weekly": "Weekly",
    "btn_add_daily": "Add daily",
    "btn_add_weekly": "Add weekly",
    "sch_start_prompt": "Send the start time (24h).\nExample · <code>22:00</code>",
    "sch_end_prompt": "Send the end time (24h). It may be after midnight.\nExample · <code>06:00</code>",
    "sch_invalid_time": "Send a time like 22:00.",
    "sch_saved": "Schedule saved.",
    "sch_deleted": "Schedule deleted.",
    "sch_detail_title": "Schedule",
    "sch_days_hint": "Tap weekdays to toggle.",
    "sch_enabled": "Enabled",
    "sch_disabled": "Disabled",
    "btn_delete_schedule": "Delete",
    "btn_enable": "Enable",
    "btn_disable": "Disable",
    "day_0": "Mon",
    "day_1": "Tue",
    "day_2": "Wed",
    "day_3": "Thu",
    "day_4": "Fri",
    "day_5": "Sat",
    "day_6": "Sun",
    "tz_line": "Time zone · {tz}",
    "exm_title": "Exemptions",
    "exm_hint": "Exempt administrators keep their rights during Shield Mode. The owner is always exempt.",
    "exm_empty": "No managed administrators.",
    "hist_title": "Shield history",
    "hist_empty": "No sessions yet.",
    "hist_row": "{glyph} {start} → {end} · {trigger}",
    "trig_manual": "manual",
    "trig_schedule": "schedule",

    # ── activity ──────────────────────────────────────────────
    "act_title": "Activity",
    "act_empty": "Nothing recorded yet.",
    "flt_all": "All",
    "flt_violations": "Violations",
    "flt_admins": "Admins",
    "flt_shield": "Shield",
    "flt_channel": "Channel",
    "vio_title": "Violations",
    "vio_empty": "No violations. Calm waters.",
    "vio_row": "{time} · {name} · {kind}",
    "vio_detail_title": "Violation",
    "vio_admin": "Administrator",
    "vio_kind": "Kind",
    "vio_rule": "Rule",
    "vio_action": "Action",
    "vio_post": "Post",
    "vio_excerpt": "Excerpt",
    "vio_api": "Moderation",
    "vio_api_line": "{model} · {category} · {severity}",
    "vio_restored": "Restored {when}",

    # ── settings ──────────────────────────────────────────────
    "set_title": "Settings",
    "set_language": "Language",
    "set_timezone": "Time zone",
    "set_managers": "Managers",
    "set_owner": "Owner",
    "btn_language": "Language",
    "btn_timezone": "Time zone",
    "btn_managers": "Managers",
    "tz_prompt": "Send an IANA time zone.\nExamples · <code>Asia/Baghdad</code> · <code>Europe/Berlin</code>",
    "tz_invalid": "Unknown time zone. Use a name like Asia/Baghdad.",
    "tz_saved": "Time zone set to {tz}.",
    "lang_title": "Language",
    "lang_en": "English",
    "lang_ar": "العربية",
    "lang_saved": "Language updated.",
    "mgr_title": "Managers",
    "mgr_hint": "Managers can use every control for this channel.",
    "mgr_row": "{name} · {role}",
    "role_owner": "owner",
    "role_manager": "manager",
    "btn_add_manager": "Add manager",
    "mgr_add_prompt": "Forward a message from the new manager or send their numeric ID.",
    "mgr_added": "Manager added.",
    "mgr_removed": "Manager removed.",
    "mgr_cannot_remove_owner": "The owner cannot be removed.",

    # ── system ────────────────────────────────────────────────
    "sys_title": "System",
    "sys_channels": "Channels",
    "sys_channels_line": "{active} active · {pending} pending · {other} other",
    "sys_moderation": "Moderation",
    "sys_moderation_line": "{used} / {budget} today · {model}",
    "sys_moderation_off": "Disabled — no API key",
    "sys_shield": "Shield sessions",
    "sys_uptime": "Uptime",
    "btn_pending": "Pending · {n}",
    "btn_all_channels": "All channels",
    "btn_sys_admins": "System admins",
    "btn_health": "Health",
    "pend_title": "Pending activation",
    "pend_empty": "No channels waiting.",
    "pend_card": "<b>{title}</b>\n<code>{id}</code>\nAdded by · {added_by}\nOwner · {owner}",
    "btn_activate": "● Activate",
    "btn_decline": "Decline",
    "activated_ok": "Channel activated.",
    "declined_ok": "Channel declined.",
    "sysc_title": "All channels",
    "sysc_row": "{glyph} {title}",
    "ch_manage_title": "Channel",
    "btn_ch_suspend": "Suspend channel",
    "btn_ch_resume": "Resume channel",
    "btn_ch_revoke": "Revoke",
    "confirm_revoke": "Revoke <b>{title}</b>?\nProtection stops. Administrators keep their current rights.",
    "ch_suspended_ok": "Channel suspended.",
    "ch_resumed_ok": "Channel resumed.",
    "ch_revoked_ok": "Channel revoked.",
    "sysa_title": "System admins",
    "sysa_hint": "System admins can activate channels and see every channel.",
    "sysa_owner": "owner",
    "sysa_admin": "admin",
    "btn_add_sysadmin": "Add system admin",
    "sysa_add_prompt": "Forward a message from the user or send their numeric ID.",
    "sysa_added": "System admin added.",
    "sysa_removed": "System admin removed.",
    "hlth_title": "Health",
    "hlth_db": "Database",
    "hlth_ok": "OK",
    "hlth_fail": "Unavailable",
    "hlth_uptime": "Uptime",
    "hlth_moderation": "Moderation API",
    "hlth_chain": "Chain",
    "hlth_requests": "Requests today",
    "hlth_last_model": "Last model",
    "hlth_last_error": "Last error",
    "hlth_cooling": "Cooling down",
    "hlth_budget_exhausted": "Daily budget exhausted",
    "hlth_key": "OpenRouter key",
    "hlth_key_line": "usage {usage} · limit {limit} · free today {free_today}",
    "hlth_media_groups": "Album buffers",
    "hlth_sessions": "Active shield sessions",

    # ── cards ─────────────────────────────────────────────────
    "card_suspended": "! Administrator access suspended",
    "card_deleted": "○ Post removed",
    "card_noticed": "! Policy violation",
    "card_could_not": "! Could not suspend · {why}",
    "why_unattributed": "post is unsigned",
    "why_unmanaged": "promoted outside Vigil",
    "why_owner": "channel owner",
    "why_bot_rights": "bot is missing rights",
    "why_telegram": "Telegram error",
    "why_already": "already suspended",
    "kind_link": "Link",
    "kind_mention": "Mention",
    "kind_forward": "Forward",
    "kind_media": "Media",
    "kind_emoji": "Premium emoji",
    "kind_language": "Language",
    "kind_length": "English length",
    "kind_content": "Content",
    "reason_link": "Link detected in post",
    "reason_mention": "Mention detected in post",
    "reason_forward": "Forwarded content",
    "reason_media": "Media outside policy",
    "reason_emoji": "Custom emoji outside the allowed pack",
    "reason_language": "Text in a language outside policy",
    "reason_length": "English text over the limit",
    "reason_content": "Flagged by moderation",
    "card_rule": "Rule",
    "card_post": "Post",
    "card_deleted_flag": "deleted",
    "card_kept_flag": "kept",
    "card_time": "Time",
    "card_channel": "Channel",
    "btn_restore_admin": "↻ Restore as administrator",
    "btn_view_admin": "◇ Administrator",
    "btn_view_violation": "◇ Details",
    "card_restored_line": "● Restored · {by} · {when}",
    "card_unsigned_name": "Unsigned post",
    "card_unknown_name": "Unknown signature “{sig}”",
    "card_ambiguous_name": "Ambiguous signature “{sig}”",
    "card_shield_on": "◉ Shield Mode is on",
    "card_shield_on_body": "{n} administrators suspended · {skipped} skipped\nEnds · {ends}",
    "ends_manual": "when you stop it",
    "card_shield_off": "○ Shield Mode is off",
    "card_shield_off_body": "{restored} restored · {failed} failed",
    "card_shield_failed_row": "! {name} · {error}",
    "btn_retry_restore": "↻ Retry failed",
    "card_api_failure": "! Moderation unavailable",
    "card_api_failure_body": "English posts are being {mode} until the API answers again.\n{error}",
    "mode_allowed": "allowed",
    "mode_blocked": "treated as violations",
    "card_unattributed": "! Posts cannot be attributed",
    "card_unattributed_body": (
        "A post arrived without a signature, so Vigil cannot tell which administrator wrote it.\n\n"
        "Turn on <b>Sign messages</b> in the channel settings and give administrators distinct titles."
    ),
    "card_ambiguous": "! Two administrators share a signature",
    "card_ambiguous_body": "“{sig}” belongs to {names}.\nGive them distinct custom titles so posts can be attributed.",
    "card_bot_rights": "! Vigil lost rights",
    "card_bot_rights_body": "Missing · {rights}\nProtection and restores are paused until they are returned.",
    "card_bot_removed": "! Vigil was removed from {title}",
    "card_bot_removed_shield": "Shield Mode was active. {n} administrators cannot be restored until Vigil is added back.",
    "card_pending": "◇ New channel awaiting activation",
    "card_activated": "● {title} is now protected",
    "card_activated_body": (
        "Protection is active. All administrator activity is now monitored.\n\n"
        "<b>Checklist</b>\n"
        "{rights_line}\n"
        "{signatures_line}\n"
        "{admins_line}"
    ),
    "chk_rights_ok": "● Bot rights complete",
    "chk_rights_missing": "! Bot missing · {rights}",
    "chk_signatures": "◇ Turn on <i>Sign messages</i> in the channel settings",
    "chk_admins_ok": "● {n} administrators under protection",
    "chk_admins_unmanaged": "! {n} administrators promoted outside Vigil · open Administrators to adopt them",
    "card_unauthorized": "This channel is not activated in Vigil yet.\n<b>{title}</b> · <code>{id}</code>\nThe system owner has been notified.",
    "channel_notice_unauthorized": "Vigil · this channel is not activated in the protection system.",
    "card_reattached": "● Vigil is back in {title}",
    "card_declined": "Activation declined for {title}.",
    "card_external_repromote": "◇ {name} was promoted again outside Vigil while suspended.",

    # ── audit action labels ───────────────────────────────────
    "au_channel.unauthorized_attempt": "Unauthorized channel attempt",
    "au_channel.activated": "Channel activated",
    "au_channel.declined": "Channel declined",
    "au_channel.suspended": "Channel suspended",
    "au_channel.resumed": "Channel resumed",
    "au_channel.revoked": "Channel revoked",
    "au_channel.bot_removed": "Bot removed",
    "au_channel.reattached": "Bot re-added",
    "au_channel.bot_rights_changed": "Bot rights changed",
    "au_admin.promoted": "Administrator promoted",
    "au_admin.demoted": "Administrator demoted",
    "au_admin.restored": "Administrator restored",
    "au_admin.restore_failed": "Restore failed",
    "au_admin.removed": "Administrator removed",
    "au_admin.removed_externally": "Administrator removed in Telegram",
    "au_admin.repromoted_externally": "Administrator re-promoted in Telegram",
    "au_admin.shield_exempt": "Shield exemption changed",
    "au_admin.reset": "Administrator status reset",
    "au_violation": "Violation",
    "au_shield.on": "Shield Mode on",
    "au_shield.off": "Shield Mode off",
    "au_shield.member_failed": "Shield restore failed",
    "au_shield.schedule_added": "Schedule added",
    "au_shield.schedule_deleted": "Schedule deleted",
    "au_shield.schedule_toggled": "Schedule toggled",
    "au_api.failure": "Moderation API failure",
    "au_telegram.failure": "Telegram API failure",
    "au_setting.changed": "Setting changed",
    "au_emoji.added": "Emoji allowed",
    "au_emoji.removed": "Emoji removed",
    "au_emoji.pack_added": "Emoji pack allowed",
    "au_emoji.pack_removed": "Emoji pack removed",
    "au_system.started": "System started",
    "au_system.admin_added": "System admin added",
    "au_system.admin_removed": "System admin removed",
    "au_manager.added": "Manager added",
    "au_manager.removed": "Manager removed",
    "au_post.unattributed": "Unsigned post",
    "au_post.ambiguous": "Ambiguous signature",
    "au_access.denied": "Access denied",
}
